/*
 * 
 * 
 */
package tiendaOrdenadores;

public class jpAñadeCoche extends javax.swing.JPanel{

    public jpAñadeCoche() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lModelo = new javax.swing.JLabel();
        tModelo = new javax.swing.JTextField();
        lCaracteristicasTecnicas = new javax.swing.JLabel();
        lMotor = new javax.swing.JLabel();
        lAerodinamica = new javax.swing.JLabel();
        lNeumaticos = new javax.swing.JLabel();
        jCMotor = new javax.swing.JComboBox();
        jCAerodinamica = new javax.swing.JComboBox();
        jCNeumaticos = new javax.swing.JComboBox();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Añadir Coche"));

        lModelo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lModelo.setText("Modelo:");

        lCaracteristicasTecnicas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lCaracteristicasTecnicas.setText("Caracteristicas Tecnicas:");

        lMotor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lMotor.setText("Motor:");

        lAerodinamica.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lAerodinamica.setText("Aerodinamica:");

        lNeumaticos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lNeumaticos.setText("Neumaticos:");

        jCMotor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));

        jCAerodinamica.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));

        jCNeumaticos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lCaracteristicasTecnicas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lAerodinamica)
                            .addComponent(lMotor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lNeumaticos, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCAerodinamica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCNeumaticos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lModelo)
                        .addGap(28, 28, 28)
                        .addComponent(tModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lModelo)
                    .addComponent(tModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCaracteristicasTecnicas)
                    .addComponent(lMotor)
                    .addComponent(jCMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lAerodinamica)
                    .addComponent(jCAerodinamica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNeumaticos)
                    .addComponent(jCNeumaticos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public String getModelo(){
        String s= "Sin Modelo";
        if (!tModelo.getText().equals("")){
            return tModelo.getText();
        }else{
            return s;
        }
    }
     
    public CaracteristicasTecnicasCoche getCaracteristicasTecnicas () { 
        float motor = jCMotor.getSelectedIndex();
        float aerodinamica = jCAerodinamica.getSelectedIndex();
        float neumaticos = jCNeumaticos.getSelectedIndex();
        
        return new CaracteristicasTecnicasCoche(motor,aerodinamica,neumaticos);               
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jCAerodinamica;
    private javax.swing.JComboBox jCMotor;
    private javax.swing.JComboBox jCNeumaticos;
    private javax.swing.JLabel lAerodinamica;
    private javax.swing.JLabel lCaracteristicasTecnicas;
    private javax.swing.JLabel lModelo;
    private javax.swing.JLabel lMotor;
    private javax.swing.JLabel lNeumaticos;
    private javax.swing.JTextField tModelo;
    // End of variables declaration//GEN-END:variables

}
