/*
 * 
 * 
 */
package tiendaOrdenadores;

public class jpAñadeCircuito extends javax.swing.JPanel{

    public jpAñadeCircuito() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        lNombre = new javax.swing.JLabel();
        tNombre = new javax.swing.JTextField();
        lAforo = new javax.swing.JLabel();
        tAforo = new javax.swing.JTextField();
        lCanon = new javax.swing.JLabel();
        tCanon = new javax.swing.JTextField();
        lNumRectas = new javax.swing.JLabel();
        tNumRectas = new javax.swing.JTextField();
        lNumCurvas = new javax.swing.JLabel();
        tNumCurvas = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Añadir Circuito"));

        lNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lNombre.setText("Nombre:");

        tNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNombreActionPerformed(evt);
            }
        });

        lAforo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lAforo.setText("Aforo:");

        lCanon.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lCanon.setText("Canon:");

        lNumRectas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lNumRectas.setText("Numero de Rectas:");

        lNumCurvas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lNumCurvas.setText("Numero de Curvas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lNumCurvas)
                        .addGap(18, 18, 18)
                        .addComponent(tNumCurvas))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lNombre)
                            .addComponent(lAforo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tAforo)
                            .addComponent(tNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lCanon)
                            .addComponent(lNumRectas))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tNumRectas)
                            .addComponent(tCanon, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNombre)
                    .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lAforo)
                    .addComponent(tAforo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCanon)
                    .addComponent(tCanon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNumRectas)
                    .addComponent(tNumRectas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNumCurvas)
                    .addComponent(tNumCurvas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNombreActionPerformed

    public String getNombre () {
        String s= "Sin Nombre";
        if (!tNombre.getText().equals("")){
            return tNombre.getText();
        }else{
            return s;
        }
    }
    
    public int getAforo () {
        int s = 0;
        if (!tAforo.getText().equals("")){
            return Integer.parseInt(tAforo.getText());
        }else{
            return s;
        }
    }
    
    public int getCanon () {
        int s = 0;
        if (!tCanon.getText().equals("")){
            return Integer.parseInt(tCanon.getText());
        }else{
            return s;
        }
    }
    
    public int getNumRectas () {
        int s=0;
        if (!tNumRectas.getText().equals("")){
            return Integer.parseInt(tNumRectas.getText());
        }else{
            return s;
        }               
    }
    
    public int getNumCurvas () {
        int s=0;
        if (!tNumCurvas.getText().equals("")){
            return Integer.parseInt(tNumCurvas.getText());
        }else{
            return s;
        }               
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JLabel lAforo;
    private javax.swing.JLabel lCanon;
    private javax.swing.JLabel lNombre;
    private javax.swing.JLabel lNumCurvas;
    private javax.swing.JLabel lNumRectas;
    private javax.swing.JTextField tAforo;
    private javax.swing.JTextField tCanon;
    private javax.swing.JTextField tNombre;
    private javax.swing.JTextField tNumCurvas;
    private javax.swing.JTextField tNumRectas;
    // End of variables declaration//GEN-END:variables

}
