/*
 * 
 * 
 */
package tiendaOrdenadores;

public class jpIntercambioPiloto extends javax.swing.JPanel {
    int idEsc;
    
    public jpIntercambioPiloto(int idEscuderia) {
        initComponents();
        idEsc= idEscuderia-1;
        int aux=0;
        for (Escuderia escuderia : Formula1UI.formula1.escuderias){
            if(aux != idEscuderia-1)
                jCEscuderias.addItem(escuderia.getNombre());
            ++aux;
        }
        
        int primerId = 0;
        if (idEscuderia-1 == 0) ++primerId;
        jCTraigo.removeAllItems();
        if(Formula1UI.formula1.escuderias.get(primerId).getNumOficiales() == 0){
            jCTraigo.addItem(0);
        }else{
            for(Piloto p : Formula1UI.formula1.escuderias.get(primerId).getOficiales()){
                jCTraigo.addItem(p.getNombre());
            }
        }
        jCCedo.removeAllItems();
        if(Formula1UI.formula1.escuderias.get(idEsc).getNumOficiales() == 0){
            jCCedo.addItem(0);
        }else{
            for(Piloto p : Formula1UI.formula1.escuderias.get(idEsc).getOficiales()){
                jCCedo.addItem(p.getNombre());
            }
        } 
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Pregunta = new javax.swing.JLabel();
        jCOficial = new javax.swing.JCheckBox();
        jCProbador = new javax.swing.JCheckBox();
        jCEscuderias = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jCCedo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jCOficial2 = new javax.swing.JCheckBox();
        jCProbador2 = new javax.swing.JCheckBox();
        jCTraigo = new javax.swing.JComboBox();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Fichar piloto de otra escuderia"));

        Pregunta.setText("¿Qué escuderia quieres mirar?");

        buttonGroup1.add(jCOficial);
        jCOficial.setSelected(true);
        jCOficial.setText("Oficial");
        jCOficial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCOficialActionPerformed(evt);
            }
        });

        buttonGroup1.add(jCProbador);
        jCProbador.setText("Probador");
        jCProbador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCProbadorActionPerformed(evt);
            }
        });

        jCEscuderias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCEscuderiasActionPerformed(evt);
            }
        });

        jLabel1.setText("¿Qué tipo de piloto quieres mirar?");

        jCCedo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0" }));

        jLabel2.setText("¿Qué piloto quieres ceder a la otra escuderia?");

        buttonGroup2.add(jCOficial2);
        jCOficial2.setSelected(true);
        jCOficial2.setText("Oficial");
        jCOficial2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCOficial2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jCProbador2);
        jCProbador2.setText("Probador");
        jCProbador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCProbador2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jCOficial2)
                                    .addGap(33, 33, 33)
                                    .addComponent(jCProbador2)
                                    .addGap(8, 8, 8)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jCCedo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jCEscuderias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(Pregunta)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jCOficial)
                                    .addGap(40, 40, 40)
                                    .addComponent(jCProbador)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jCTraigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pregunta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCEscuderias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCOficial)
                    .addComponent(jCProbador))
                .addGap(18, 18, 18)
                .addComponent(jCTraigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCOficial2)
                    .addComponent(jCProbador2))
                .addGap(18, 18, 18)
                .addComponent(jCCedo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCEscuderiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCEscuderiasActionPerformed
        jCTraigo.removeAllItems();
        int id = jCEscuderias.getSelectedIndex();
        if (id >= idEsc) ++id;
        
        if(jCOficial.isSelected()){
            if(Formula1UI.formula1.escuderias.get(id).getNumOficiales() == 0){
                jCTraigo.addItem(0);
            }else{
                for(Piloto p : Formula1UI.formula1.escuderias.get(id).getOficiales()){
                    jCTraigo.addItem(p.getNombre());
                }
            }            
        }else{
            if(Formula1UI.formula1.escuderias.get(id).getNumProbadores() == 0){
                jCTraigo.addItem(0);
            }else{
                for(Piloto p : Formula1UI.formula1.escuderias.get(id).getProbadores()){
                    jCTraigo.addItem(p.getNombre());
                }
            }           
        }
    }//GEN-LAST:event_jCEscuderiasActionPerformed

    private void jCOficialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCOficialActionPerformed
        jCTraigo.removeAllItems();
        int id = jCEscuderias.getSelectedIndex();
        if (id >= idEsc) ++id;
        
        if(Formula1UI.formula1.escuderias.get(id).getNumOficiales() == 0){
            jCTraigo.addItem(0);
        }else{
            for(Piloto p : Formula1UI.formula1.escuderias.get(id).getOficiales()){
                    jCTraigo.addItem(p.getNombre());
            } 
        }               
    }//GEN-LAST:event_jCOficialActionPerformed

    private void jCProbadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCProbadorActionPerformed
        jCTraigo.removeAllItems();
        int id = jCEscuderias.getSelectedIndex();
        if (id >= idEsc) ++id;
        
         if(Formula1UI.formula1.escuderias.get(id).getNumProbadores() == 0){
            jCTraigo.addItem(0);
        }else{
            for(Piloto p : Formula1UI.formula1.escuderias.get(id).getProbadores()){
                    jCTraigo.addItem(p.getNombre());
            }
         }               
    }//GEN-LAST:event_jCProbadorActionPerformed

    private void jCOficial2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCOficial2ActionPerformed
        jCCedo.removeAllItems();
        
        if(Formula1UI.formula1.escuderias.get(idEsc).getNumOficiales() == 0){
            jCCedo.addItem(0);
        }else{
            for(Piloto p : Formula1UI.formula1.escuderias.get(idEsc).getOficiales()){
                    jCCedo.addItem(p.getNombre());
            } 
        }
    }//GEN-LAST:event_jCOficial2ActionPerformed

    private void jCProbador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCProbador2ActionPerformed
        jCCedo.removeAllItems();
        
        if(Formula1UI.formula1.escuderias.get(idEsc).getNumProbadores() == 0){
            jCCedo.addItem(0);
        }else{
            for(Piloto p : Formula1UI.formula1.escuderias.get(idEsc).getProbadores()){
                    jCCedo.addItem(p.getNombre());
            } 
        }
    }//GEN-LAST:event_jCProbador2ActionPerformed

    public int getEscuderia(){
         if (jCEscuderias.getSelectedIndex() >= idEsc) return jCEscuderias.getSelectedIndex()+1;
            
         return jCEscuderias.getSelectedIndex();
    }
     
    public int getCedo(){
       if (jCCedo.getItemAt(0).equals(0))return -1;
       return jCCedo.getSelectedIndex();
    }
    
    public int getTraigo(){
       if (jCTraigo.getItemAt(0).equals(0))return -1;
       return jCTraigo.getSelectedIndex();
    }
    
    public boolean getOficial(){
       return jCOficial2.isSelected(); 
    }
    
    public boolean oficial(){
       return jCOficial.isSelected(); 
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Pregunta;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox jCCedo;
    private javax.swing.JComboBox jCEscuderias;
    private javax.swing.JCheckBox jCOficial;
    private javax.swing.JCheckBox jCOficial2;
    private javax.swing.JCheckBox jCProbador;
    private javax.swing.JCheckBox jCProbador2;
    private javax.swing.JComboBox jCTraigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
