/*
 * 
 * 
 */
package tiendaOrdenadores;

public class jpRobarPiloto extends javax.swing.JPanel {
    int idEsc;
    
    public jpRobarPiloto(int idEscuderia) {
        initComponents();
        idEsc= idEscuderia-1;
        int aux=0;
        for (Escuderia escuderia : Formula1UI.formula1.escuderias){
            if(aux != idEscuderia-1)
                jCEscuderias.addItem(escuderia.getNombre());
            ++aux;
        }
        
        int primerId = 0;
        if (idEscuderia-1 == 0) ++primerId;
        jCId.removeAllItems();
        if(Formula1UI.formula1.escuderias.get(primerId).getNumOficiales() == 0){
            jCId.addItem(0);
        }else{
            for (int num =1; num < Formula1UI.formula1.escuderias.get(primerId).getNumOficiales()+1; ++num){
                jCId.addItem(num);
            }
        }
        
        listapilotos.setText(Formula1UI.formula1.escuderias.get(primerId).mostrarOficiales()
         +"El numero total de pilotos es: " + Formula1UI.formula1.escuderias.get(primerId).getNumOficiales());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listapilotos = new javax.swing.JTextArea();
        lidPiloto = new javax.swing.JLabel();
        Pregunta = new javax.swing.JLabel();
        jCOficial = new javax.swing.JCheckBox();
        jCProbador = new javax.swing.JCheckBox();
        jCEscuderias = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jCId = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jCOficial2 = new javax.swing.JCheckBox();
        jCProbador2 = new javax.swing.JCheckBox();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Fichar piloto de otra escuderia"));

        listapilotos.setColumns(20);
        listapilotos.setRows(5);
        jScrollPane1.setViewportView(listapilotos);

        lidPiloto.setText("Identificador del piloto a fichar:");

        Pregunta.setText("¿Qué escuderia quieres mirar?");

        buttonGroup1.add(jCOficial);
        jCOficial.setSelected(true);
        jCOficial.setText("Oficial");
        jCOficial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCOficialActionPerformed(evt);
            }
        });

        buttonGroup1.add(jCProbador);
        jCProbador.setText("Probador");
        jCProbador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCProbadorActionPerformed(evt);
            }
        });

        jCEscuderias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCEscuderiasActionPerformed(evt);
            }
        });

        jLabel1.setText("¿Qué tipo de piloto quieres mirar?");

        jCId.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0" }));

        jLabel2.setText("¿Qué tipo de contrato le quieres hacer?");

        buttonGroup2.add(jCOficial2);
        jCOficial2.setSelected(true);
        jCOficial2.setText("Oficial");

        buttonGroup2.add(jCProbador2);
        jCProbador2.setText("Probador");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(335, 335, 335)
                                .addComponent(jCEscuderias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(285, 285, 285)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(Pregunta)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jCOficial)
                                            .addGap(40, 40, 40)
                                            .addComponent(jCProbador))
                                        .addComponent(jLabel2)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jCOficial2)
                                            .addGap(40, 40, 40)
                                            .addComponent(jCProbador2))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(lidPiloto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(Pregunta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCEscuderias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCOficial)
                    .addComponent(jCProbador))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lidPiloto)
                    .addComponent(jCId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCOficial2)
                    .addComponent(jCProbador2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCEscuderiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCEscuderiasActionPerformed
        jCId.removeAllItems();
        int id = jCEscuderias.getSelectedIndex();
        if (id >= idEsc) ++id;
        
        if(jCOficial.isSelected()){
            if(Formula1UI.formula1.escuderias.get(id).getNumOficiales() == 0){
                jCId.addItem(0);
            }else{
                for (int num =1; num < Formula1UI.formula1.escuderias.get(id).getNumOficiales()+1; ++num){
                    jCId.addItem(num);
                }
            }
            listapilotos.setText(Formula1UI.formula1.escuderias.get(id).mostrarOficiales()
             +"El numero total de pilotos es: " + Formula1UI.formula1.escuderias.get(id).getNumOficiales());
        }else{
            if(Formula1UI.formula1.escuderias.get(id).getNumProbadores() == 0){
                jCId.addItem(0);
            }else{
                for (int num =1; num < Formula1UI.formula1.escuderias.get(id).getNumProbadores()+1; ++num){
                    jCId.addItem(num);
                }
            }
            listapilotos.setText(Formula1UI.formula1.escuderias.get(id).mostrarProbadores()
             +"El numero total de pilotos es: " + Formula1UI.formula1.escuderias.get(id).getNumProbadores());
        }
    }//GEN-LAST:event_jCEscuderiasActionPerformed

    private void jCOficialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCOficialActionPerformed
        jCId.removeAllItems();
        int id = jCEscuderias.getSelectedIndex();
        if (id >= idEsc) ++id;
        
        if(Formula1UI.formula1.escuderias.get(id).getNumOficiales() == 0){
            jCId.addItem(0);
        }else{
            for (int num =1; num < Formula1UI.formula1.escuderias.get(id).getNumOficiales()+1; ++num){
                    jCId.addItem(num);
            } 
        }
        
        listapilotos.setText(Formula1UI.formula1.escuderias.get(id).mostrarOficiales()
        +"El numero total de pilotos es: " + Formula1UI.formula1.escuderias.get(id).getNumOficiales());
    }//GEN-LAST:event_jCOficialActionPerformed

    private void jCProbadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCProbadorActionPerformed
        jCId.removeAllItems();
        int id = jCEscuderias.getSelectedIndex();
        if (id >= idEsc) ++id;
        
         if(Formula1UI.formula1.escuderias.get(id).getNumProbadores() == 0){
            jCId.addItem(0);
        }else{
            for (int num =1; num < Formula1UI.formula1.escuderias.get(id).getNumProbadores()+1; ++num){
                    jCId.addItem(num);
            }
         }
        
        listapilotos.setText(Formula1UI.formula1.escuderias.get(id).mostrarProbadores()
        +"El numero total de pilotos es: " + Formula1UI.formula1.escuderias.get(id).getNumProbadores());
    }//GEN-LAST:event_jCProbadorActionPerformed

    public int getEscuderia(){
         if (jCEscuderias.getSelectedIndex() >= idEsc) return jCEscuderias.getSelectedIndex()+1;
            
         return jCEscuderias.getSelectedIndex();
    }
     
    public int getNumero(){
       if (jCId.getItemAt(0).equals(0))return -1;
       return jCId.getSelectedIndex();
    }
    
    public boolean getOficial(){
       return jCOficial2.isSelected(); 
    }
    
    public boolean oficial(){
       return jCOficial.isSelected(); 
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Pregunta;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox jCEscuderias;
    private javax.swing.JComboBox jCId;
    private javax.swing.JCheckBox jCOficial;
    private javax.swing.JCheckBox jCOficial2;
    private javax.swing.JCheckBox jCProbador;
    private javax.swing.JCheckBox jCProbador2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lidPiloto;
    private javax.swing.JTextArea listapilotos;
    // End of variables declaration//GEN-END:variables

}
