package tiendaOrdenadores;

import java.io.*;
import javax.swing.JOptionPane;

public class TiendaOrdenadoresUI extends javax.swing.JFrame {

    static TiendaOrdenadores tiendaOrdenadores;
    
    public TiendaOrdenadoresUI() {
        tiendaOrdenadores = new TiendaOrdenadores();
        initComponents();
        this.setTitle ("Tienda de Ordenadores");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bAdministrador = new javax.swing.JButton();
        bEncargado = new javax.swing.JButton();
        bVendedor = new javax.swing.JButton();
        bGuarda = new javax.swing.JButton();
        bCargar = new javax.swing.JButton();
        jAviso = new javax.swing.JLabel();
        Imagen = new javax.swing.JLabel();
        Cliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bAdministrador.setText("Administrador");
        bAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAdministradorActionPerformed(evt);
            }
        });

        bEncargado.setText("Encargado");
        bEncargado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEncargadoActionPerformed(evt);
            }
        });

        bVendedor.setText("Vendedor");
        bVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVendedorActionPerformed(evt);
            }
        });

        bGuarda.setText("Guardar Tienda Ordenadores");
        bGuarda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardaActionPerformed(evt);
            }
        });

        bCargar.setText("Cargar Tienda Ordenadores");
        bCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCargarActionPerformed(evt);
            }
        });

        Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tiendaOrdenadores/logo.png"))); // NOI18N

        Cliente.setText("Cliente");
        Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(Imagen))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bVendedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bAdministrador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bEncargado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 116, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bGuarda)
                                .addGap(27, 27, 27)
                                .addComponent(bCargar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jAviso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Imagen)
                .addGap(18, 18, 18)
                .addComponent(bAdministrador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bEncargado)
                .addGap(13, 13, 13)
                .addComponent(bVendedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Cliente)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCargar)
                    .addComponent(bGuarda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bEncargadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEncargadoActionPerformed
        if(!TiendaOrdenadoresUI.tiendaOrdenadores.tiendas.isEmpty()){
            jpConsultaTienda pConsulta = new jpConsultaTienda();
            if(JOptionPane.showConfirmDialog(this, pConsulta, "Informacion Tienda",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE)
                == JOptionPane.OK_OPTION) {
                    if ((pConsulta.getNumero()>0) && (pConsulta.getNumero()<TiendaOrdenadoresUI.tiendaOrdenadores.tiendas.size()+1)){
                        jAviso.setText ("");
                        jpTienda pTienda = new jpTienda(pConsulta.getNumero());
                        pTienda.setVisible(true);
                    }else{
                        jAviso.setText ("El identificador de tienda no es correcto");
                    }
            }
        }else{
           jAviso.setText ("No hay tiendas");
        }
    }//GEN-LAST:event_bEncargadoActionPerformed

    private void bVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVendedorActionPerformed
        //jpMundial pMundial = new jpMundial();
        //formula1.crearMundial();
        //pMundial.setVisible (true);
    }//GEN-LAST:event_bVendedorActionPerformed

    private void bAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAdministradorActionPerformed
        jpAdmin pAdmin = new jpAdmin();
        pAdmin.setVisible (true);
    }//GEN-LAST:event_bAdministradorActionPerformed

    private void bGuardaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardaActionPerformed
        pArchivo archivo = new pArchivo();

        if(JOptionPane.showConfirmDialog(this, archivo, "Introduzca directorio",
        JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE)
        == JOptionPane.OK_OPTION){
        Ficheros fichero= new Ficheros();
        try {
            fichero.abrirEscribir(archivo.getDirectorio());
            fichero.escribir(tiendaOrdenadores);
            fichero.cerrar();
            jAviso.setText ("Se ha guardado Formula 1 en: " + archivo.getDirectorio());
        } catch (FileNotFoundException ex1) {
            jAviso.setText(ex1.getMessage());
        } catch (IOException ex2) {
            jAviso.setText(ex2.getMessage());
            System.out.println(ex2.getMessage());
        }
        }
    }//GEN-LAST:event_bGuardaActionPerformed

    private void bCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCargarActionPerformed
        pArchivo archivo = new pArchivo();

        if(JOptionPane.showConfirmDialog(this, archivo, "Introduzca directorio",
        JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE)
        == JOptionPane.OK_OPTION){
            try {
                Ficheros fichero = new Ficheros();
                fichero.abrirLeer(archivo.getDirectorio());
                tiendaOrdenadores = fichero.leer();
                fichero.cerrar();
                jAviso.setText("Se ha cargado " + archivo.getDirectorio());
            } catch (IOException ex) {
                jAviso.setText(ex.getMessage());
            } catch (ClassNotFoundException ex1) {
                jAviso.setText(ex1.getMessage());
            }

        }
    }//GEN-LAST:event_bCargarActionPerformed

    private void ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClienteActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TiendaOrdenadoresUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cliente;
    private javax.swing.JLabel Imagen;
    private javax.swing.JButton bAdministrador;
    private javax.swing.JButton bCargar;
    private javax.swing.JButton bEncargado;
    private javax.swing.JButton bGuarda;
    private javax.swing.JButton bVendedor;
    private javax.swing.JLabel jAviso;
    // End of variables declaration//GEN-END:variables

}
